# Generated by Django 4.0.4 on 2022-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='warning',
            field=models.IntegerField(choices=[(0, 'No Warning'), (1, 'First Warning'), (2, 'Final Warning')], default=0),
        ),
    ]
