from .account_view import *
from .announcement_view import *
from .document_views import *
from .grades_view import *
from .registration_view import *
from .student_homepage import *
from .test_views import *
from .planner_view import *
from .my_schedule_views import *